### ISSUE TITLE
Add PHP8 Support and Laravel 8

### ISSUE THREAD

**Issue by skalec** [CmdrSharp/netbox-laravel#2]
Hi i want to install this package an an Laravel8 running under PHP 8.0.8.
I Get the following message:

`Package cmdrsharp/netbox-laravel has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version`

**Comment by CmdrSharp** [comment]
Hi! The version requirements for the package don't constrain it - it specifies >= 7.4. I just tested creating a new Laravel project using the latest dist, on PHP 8.0.10, and the package installed successfully using `composer require cmdrsharp/netbox-laravel`

Is it possible that you are running the composer-application itself with a PHP version lower than 7.4?

**Comment by skalec** [comment]
sry for my late response. You info was right. I had local PHP 7.3 and update to 7.4 and the plugin was installed.

**Comment by CmdrSharp** [comment]
No problem at all, thank you for confirming :)
